# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-collection-crud"
client_id = "4487fe4c899dd85ac8c4e2d1e30f305f"
application_url = "https://lift-jury-finals-seasons.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lift-jury-finals-seasons.trycloudflare.com/auth/callback",
  "https://lift-jury-finals-seasons.trycloudflare.com/auth/shopify/callback",
  "https://lift-jury-finals-seasons.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appdeveloplearn.myshopify.com"
